name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: zulu@1.8
    - uses: coursier/cache-action@v3
    - run: |
        cd hikaritest
        sbt universal:packageBin
        mv target/universal/*.zip ..
    - uses: actions/upload-artifact@v2
      with:
        name: hikaritest
        path: hikaritest-*.zip
